version: "3"

services:
  vpnclient:
    container_name: vpnclient
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - 1337:1337
    - 1338:1338
    cap_add: 
    - NET_ADMIN